# GM12878 H3k4me3 signal test

context_length: 5000
fibers_per_entry: 100
num_sample_ccres: -1
bulk_name: h3k4me3_p
seed: 919
assay: h3k4me3

cell_types:
  GM12878:
    ratio: 1.0
dataset_type: single
