# mixed cell h3k4me3_sig

context_length: 5000
fibers_per_entry: 200
num_sample_ccres: -1
bulk_name: "h3k4me3_sig"
seed: 919

metadata:
  fasta_path: "/home/azr/projects/def-maxwl/azr/data/misc/hg38.fa"
  ccre_path: "/home/azr/projects/def-maxwl/azr/data/misc/grch38_ccres.bed"
  val_chrs: ["chr21"]
  fiber_base_path: "/home/azr/projects/def-maxwl/azr/data/DATA_FIBER/fiber_multi_cell"
  bulk_base_path: "/home/azr/projects/def-maxwl/azr/data/DATA_FIBER/h3k4me3_multi_cell/"
  cell_types:
    GM12878:
      fibers: "GM12878-fire-v0.1-filtered.cram"
      bulk: "GM12878_ENCFF012DMX_H3K4me3_signal.bigWig"
      ratio: 0.5
    K562:
      fibers: "K562_Fiber_seq_200U_1M_cells_200U_PS01370-fire-v0.1-filtered.cram"
      bulk: "K562_ENCFF071GML_H3K4me3_signal.bigWig"
      ratio: 0.5
