# mixed cell atac_fcc

context_length: 5000
fibers_per_entry: 100
num_sample_ccres: -1
bulk_name: ATAC_seq_fcc
seed: 919
assay: atac

cell_types:
  GM12878:
    ratio: 0.5
  K562:
    ratio: 0.5
dataset_type: mixed
